{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:S256Test", "name": "test_sec", "time": 0.07552814483642578, "type": "failure", "errtype": "builtins.AssertionError", "message": "b'\\x02\\x9d\\\\\\xa4\\x96p\\xcb\\xe4\\xc3\\xbf\\xa8L\\x96[55 chars]\\xd5' != b'\\x03\\x9d\\\\\\xa4\\x96p\\xcb\\xe4\\xc3\\xbf\\xa8L\\x96[55 chars]\\xd5'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/pbhacking/sec-format-jsong-pb-denver-070918/test/index_test.py\", line 17, in test_sec\n    self.assertEqual(point.sec(compressed=True), bytes.fromhex(compressed))\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: b'\\x02\\x9d\\\\\\xa4\\x96p\\xcb\\xe4\\xc3\\xbf\\xa8L\\x96[55 chars]\\xd5' != b'\\x03\\x9d\\\\\\xa4\\x96p\\xcb\\xe4\\xc3\\xbf\\xa8L\\x96[55 chars]\\xd5'\n"}]}